# Generated by Django 5.0.2 on 2024-03-04 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title'], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
